### ISSUE TITLE
Data corruption in memory slots

### ISSUE THREAD

**Issue by VKapicyn** [mudgen/diamond-3#29]
Hi Nick!
Thanks for your idea - Brilliant Proxy :)

Do you know are there any ways to avoid problems with carruption of data?

For example, we have two structs with one pointer:

    bytes32 constant POINTER = keccak256("any.pointer");
    
    struct DataStruct {
        uint32 value;
        mapping(address => uint256) authsIndex;
        address[] auths;
    }

    struct DataStructV2 {
        uint256 value;
    }

    function getDataStruct() internal pure returns (DataStruct storage ds) {
        bytes32 position = POINTER;
        assembly {
            ds.slot := position
        }
    }

    function getDataStructV2() internal pure returns (DataStructV2 storage ds) {
        bytes32 position = POINTER;
        assembly {
            ds.slot := position
        }
    }

If i write `0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF` in `ds.DataStruct2.value`, after writing `341234` in `ds.DataStruct.value`, then the second value overrides the first one. But its not ok)

Are there any ways to protect against overwriting old data with an other(new) struct in memory slot already occupied?

**Comment by mudgen** [comment]
Yes, the way to prevent data corruption is to use unique strings for different structs.  This is very easy to do.  This same approach is used by programming languages like Java to share programming libraries and projects without conflict.  Java and such programming languages call it namespaces, for example:  "com.mywebsite.myproject".

More info here: https://dev.to/mudgen/how-diamond-storage-works-90e

**Comment by VKapicyn** [comment]
Yep, I understand that for different structs - different pointers :)

But if I have a big project and a big team working on it, the risk of making a mistake (using the same pointer twice) is very high!  Are there any ways to protect yourself from such an error and loss of data, other than "just don't do it"?

**Comment by mudgen** [comment]
Hi @VKapicyn,

Hey, okay. One thing to understand is that a diamond storage pointer string only has to be unique within the diamond that it is within, not across all diamonds. 

To answer your question, there are a couple of options. One option, which is more difficult (but on the other hand you have developer resources) is to develop a tool that checks for different structs using the same diamond storage string.

Another easier option is to use a naming system that guarantees unique diamond storage pointers -- no matter how large a code base or the number of people involved.  As long as the naming system is used there is no possibility of using the same name twice for different structs.

One such naming system is this:  Make a keccak256 hash of the original string representation of a struct and use that as the pointer for the struct. 

Another naming system would be to keccak256 hash the original source code that creates and/or uses a diamond storage struct and use that as the pointer.

Another naming system could be to use the name of a struct, plus the name of the Solidity library or contract file, plus its full directory path, plus the name of the author, plus the date and time and hash that and use that as the pointer.

It doesn't really matter how large the diamond storage string or data is if it is hashed with keccak256 and assigned to a constant because this computation will be done at compile time instead of runtime.

I'm interested to know more about what you are building.

**Comment by VKapicyn** [comment]
Thanks for the ideas!

We'll probably choose the first option.
About the project, I can not tell yet, bcs NDA :)

In a few months we will publish it as open source - if you are interested, we will send you a link to source code

**Comment by mudgen** [comment]
Awesome. Yes, I'm interested to get a link to the source code when it is published.
